name: Report an Issue
description: Report an issue with Plone Documentation
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report!
  - type: textarea
    id: documentation-url
    attributes:
      label: Links of affected pages in Plone Documentation, if any.
      value: |
        - Link_1
        - Link_2
        - ...
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Include screenshots and any other helpful information.
    validations:
      required: true
